"""create telemetry table

Revision ID: ad9321992892
Revises: c0f1a42e0e38
Create Date: 2026-10-06 15:31:03.166200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9321992892'
down_revision: Union[str, Sequence[str], None] = 'c0f1a42e0e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('gas', sa.Integer(), nullable=False),
    sa.Column('presence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetries_created_at'), 'telemetries', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetries_device_id'), 'telemetries', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetries_device_id'), table_name='telemetries')
    op.drop_index(op.f('ix_telemetries_created_at'), table_name='telemetries')
    op.drop_table('telemetries')
    # ### end Alembic commands ###
